### ISSUE TITLE
mdadm 's dependency libreport

### ISSUE THREAD

**Issue by markVnl** [NethServer/arm-dev#1]
netherserver-base and nethserver-lib require mdadm. 

mdadm is build,  it’s dependency libreport still has to be build (missing build dep’s)
To get a prove of concept a dummy package is provided (ugh).

**Comment by dz00te** [comment]
reference:
https://github.com/NethServer/dev/issues/5031

**Comment by markVnl** [comment]
Dependency dropped nethserver-base > 80
