### ISSUE TITLE
Failure of templates expansion containing /usr/lib64 (part 2)

### ISSUE THREAD

**Issue by markVnl** [NethServer/arm-dev#28]
Some templates have configuration lines referring to /usr/lib64, obviously absent on arm32 bit .

**known to be affected:**

- nethserver-openvpn
- nethserver-webproxy

This is mitigated by adding a link from /usr/lib64 to /usr/lib so we did not need to change all package that uses it (See arm-dev https://github.com/markVnl/nethserver-arm-dev/issues/26, https://github.com/markVnl/nethserver-arm-dev/issues/16 and https://github.com/markVnl/nethserver-arm-dev/issues/19)

With the complete integration of arm in the nethsever-ecosystem it is preferred fo find a more elegant solution :)

**DoTo:** 
open issues for 
- [x] nethserver-openvpn
- [x] nethserver-webproxy

revisit solution in 
- [ ] [nethserver-sogo](https://github.com/NethServer/nethserver-sogo/blob/master/root/etc/e-smith/templates/etc/httpd/conf.d/zzz_SOGo.conf/10base#L4)

**Comment by DavidePrincipi** [comment]
@markVnl both related issues were closed: can we close this one too?

**Comment by gsanchietti** [comment]
Yes, closing.
