### ISSUE TITLE
restic: add arm support

### ISSUE THREAD

**Issue by dz00te** [NethServer/arm-dev#29]
while probably not so elegant,  can we add to spec of restic something like this to make multi arch ?

```
%ifarch %{arm}
%define nsarch arm
%endif
%ifarch aarch64
%define nsarch arm64
%endif
%ifarch x86_64
%define nsarch amd64
%endif
Source0: https://github.com/restic/restic/releases/download/v%{version}/restic_%{version}_linux_%{nsarch}.bz2
```

or i could upload in testing the build for aarch64 and armhfp?

**Comment by gsanchietti** [comment]
I like the patch, it should be good for all environment.

Just open the PR, then you need to manually build/upload for aarch64 and armhfp (you should already have the permissions to do it).

**Comment by dz00te** [comment]
ok, just do not go away, I might need some help :)

**Comment by dz00te** [comment]
builded and uploaded packakages for armhfp and aarch64 in arm-testing

**Comment by markVnl** [comment]
> builded and uploaded packakages for armhfp and aarch64 in arm-testing

Can we move the packages to updates?

**Comment by gsanchietti** [comment]
Done ;)
