### ISSUE TITLE
Unable to install or update rpm's on armhfp/aarch64 with 7.7.1908

### ISSUE THREAD

**Issue by markVnl** [NethServer/arm-dev#31]
Centos 7.7.1908 armhfp repositories have an extra gpg key as can be seen in the Centos-Base.repo (truncated): 

```
# cat /etc/yum.repos.d/CentOS-Base.repo

# CentOS-Base.repo
...
...
[base]
name=CentOS-$releasever - Base
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
#baseurl=http://mirror.centos.org/altarch/$releasever/os/$basearch/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
       file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-AltArch-Arm32
```

Note the additional RPM-GPG-KEY-CentOS-SIG-AltArch-Arm32 which is  absent in the (expanded)  `/etc/yum.repos.d/NethServer.repo`

Possible solutions:

1.  distribute arch depended nethserver-release packages
2.  expand /etc/yum.repos.d/NethServer.repo with some arch conditionals still have to do some (dirty) stuff with rpm macro's if installed with nethserver-install on centos base.

1/2. only distribute arch depended nethserver-release packages for installing on centos base, updates       of nethserver-release are are arch independent

cc/ @DavidePrincipi

**Comment by DavidePrincipi** [comment]
I'd go with solution 2, by changing only the template code. If file `RPM-GPG-KEY-CentOS-SIG-AltArch-Arm32` exists, expand its reference under `gpgkey=`.

**Comment by markVnl** [comment]
> I'd go with solution 2,

Oke i'll work on this first so we can get a RC image out;

And then we figure out a solution for the "nethserver-install on centos base" scenario, I think we can magage this in the nethserver-install script. It turns out the system does not break after instlling nethserver-release befor running nethserver-install. It seems just to ignore the ce-base and ce-update declarations as long the Centos-... repo's are enabled

EDIT:
we do not disable the default centos repo's at installing the netserver core modules so we are probably good to for the nethsever-install after all.
https://github.com/NethServer/nethserver-release/blob/master/root/usr/sbin/nethserver-install#L129

**Comment by markVnl** [comment]
more or less the same applies to aarch64 from `CentoOS-Base.repo `(truncated):

```
[base]
name=CentOS-$releasever - Base
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
#baseurl=http://mirror.centos.org/altarch/$releasever/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
       file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7-aarch64
```

**Comment by markVnl** [comment]
How do we proceed, should I open an issue in /dev referencing this to start QA? 

It is the vital missing part to proceed with making / publishing armhfp 7.7.1908 images , aarch64 needs a little work but is also close..

**Comment by DavidePrincipi** [comment]
I've already tested it on x86_64. If it's ok on the ARM side I can proceed with a new RPM release.

Please, add the "verified" label when ready.

**Comment by markVnl** [comment]
As you might had noticed on the picture @ https://community.nethserver.org/t/teaser-nethserver-cockpit-on-arm/13543  it already states "NethServer release 7.7.1908 **(final)**"

It was already installed and working , tested aach64 too

**Comment by markVnl** [comment]
> It is the vital missing part to proceed with making / publishing armhfp 7.7.1908 images

a gentle bump; when can we expect a new nethserver-release to be released?

cc/ @DavidePrincipi @gsanchietti

**Comment by DavidePrincipi** [comment]
Shall we wait for #32?

I expect nethserver-cockpit is working within the ARM image...

**Comment by markVnl** [comment]
> 
> 
> Shall we wait for #32?
> 
> I expect nethserver-cockpit is working within the ARM image...

The chicken or the egg paradox is, 
we cannot ask for tests for #32 simply because without this you cannot install a single package..

ATM I patch every install i make manually to be able to test, somehow the autobuild packages did not make it to the testing repository's....

**EDIT, Proposal:**
release this and release (bootable) RC1 images so others can do testing too and follow up with final images asap

**Comment by DavidePrincipi** [comment]
In nethserver-updates:

- http://mirror.nethserver.org/nethserver/7.7.1908/updates/x86_64/Packages/nethserver-release-7-16.ns7.noarch.rpm
- http://mirror.nethserver.org/nethserver/7.7.1908/updates/armhfp/Packages/nethserver-release-7-16.ns7.noarch.rpm
- http://mirror.nethserver.org/nethserver/7.7.1908/updates/aarch64/Packages/nethserver-release-7-16.ns7.noarch.rpm
