### ISSUE TITLE
Cockpit Dashboard empty hardware/info

### ISSUE THREAD

**Issue by dz00te** [NethServer/arm-dev#34]
Module: nethserver-cockpit

hardware/cpu fileds in Cockpit Dashboard  on ARM are empty. 
See also the previous issue #4  for NethGui

**Comment by dz00te** [comment]
just adapted what done from @markVnl for nethgui, it seems to work...
https://github.com/dz00te/nethserver-cockpit/commit/a7cebcec83e404499a676c517d2661efbbfd54ef

**Comment by gsanchietti** [comment]
Excellent, please open a PR! ;)

**Comment by markVnl** [comment]
Yes this should work!
<s>Now the question if it is accepted in "upstream" x86_64? </s>
EDIT cross post: it is accepted


/cc @gsanchietti @edospadoni 

PS: a little clean up off the code may be possible to:

The function readDMI() is called without an argument, meaning the _$id_ variable could be removed in the declaration of the function 
https://github.com/dz00te/nethserver-cockpit/blob/a7cebcec83e404499a676c517d2661efbbfd54ef/api/system-status/read#L74

**Comment by dz00te** [comment]
> PS: a little clean up off the code may be possible to:

tnx! i have corrected some other things... 

https://github.com/dz00te/nethserver-cockpit/commit/8c3c8e17b4102dfb04e9ee6ab95594413ebc860c

**Comment by dz00te** [comment]
fork synced and merged. still works on rpi/odroid/pine. before make a PR i would like to have some other tests on x86, i'll ask also on forum

**Comment by DavidePrincipi** [comment]
@dz00te , any update?

**Comment by dz00te** [comment]
i did not have feedbak from forum. i've just resynced my fork, and still seems ok to me... i would make the PR if you agree...

**Comment by dz00te** [comment]
all ok with nethserver-cockpit-1.3.15-1. tnx
