### ISSUE TITLE
Hotspot problem

### ISSUE THREAD

**Issue by truefriend-cz** [NethServer/arm-dev#43]
After clean flashing not install Hotspot Dedalo package.
R Pi 4B 4GB

Ended with error:
```
This command is bad:
system-packages/update
```

Tested on version: 7.8.2003 Final, 7.8.2003 RC2, 7.8.2003 RC1
Version 7.7.1908 RC1 worked ok

**Comment by markVnl** [comment]
Have to admit not to be familiar with the package; 
although the error you mention seems to be from the package-manager (yum) so will look in this first

**Comment by markVnl** [comment]
Seems to be stale,

Closing now, reopen if new Info arrives.
