### ISSUE TITLE
Groups (comps) are missing after uploads to arm-updates and arm-nethforge repo's

### ISSUE THREAD

**Issue by markVnl** [NethServer/arm-dev#48]
After uploading nethserver-arm-extra-config-1.1.0-1 to armhfp and aarch64 the groups in the updates repo’s are missing again. The groups are also missing in nethforge armhfp and aarch64 repo’s after uploading nethserver-sogo and it’s dependencies to those repositories…

Command typically run to upload:
`upload-rpms  markvnl@packages.nethserver.org:nscom/7.9.2009/arm-updates/ *.rpm` 

since #47 it's not working as it used to...

**Comment by markVnl** [comment]
@DavidePrincipi not in a particular hurry :) 

Is there a status update on this?

**Comment by DavidePrincipi** [comment]
I should look at the repo scripts in the next days, to analyze this issue and also evaluate GitHub actions as alternative to TravisCI.com

**Comment by DavidePrincipi** [comment]
Hi Mark I think I found the issue origin. Please try again the upload... :crossed_fingers:

**Comment by markVnl** [comment]
Yes can confirm it worked:

After uploading nethserver-arm-extra-config-1.1.2-1 to armhfp and aarch64 groups files are present!

Thanks
